name: Create Issue Branch

on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]

jobs:
  create-branch:
    if: github.event.comment.body == '/create-branch' || github.event_name == 'issues'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: robvanderleek/create-issue-branch@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
